"""
GPU Instance Library — per-GPU on-demand hourly pricing for inference
Pricing as of August 25, 2026

Sources: aws.amazon.com, cloud.google.com, prices.azure.com,
         coreweave.com, crusoe.ai, lambda.ai, runpod.io,
         together.ai, vast.ai
"""

GPU_LIBRARY = {
    # ── AWS ──────────────────────────────────────────────────────────────────
    "AWS - A100 40GB - p4d.24xlarge":       {"provider": "AWS",       "gpu": "A100",  "cost_hr": 2.75,  "vram_gb": 40,  "notes": "8-GPU node, ~$21.96/hr total"},
    "AWS - A100 80GB - p4de.24xlarge":      {"provider": "AWS",       "gpu": "A100",  "cost_hr": 3.43,  "vram_gb": 80,  "notes": "8-GPU node, ~$27.45/hr total"},
    "AWS - B200 - p6-b200.48xlarge":        {"provider": "AWS",       "gpu": "B200",  "cost_hr": 14.24, "vram_gb": 192, "notes": "8-GPU node, ~$113.93/hr total"},
    "AWS - B300 - p6-b300.48xlarge":        {"provider": "AWS",       "gpu": "B300",  "cost_hr": 17.80, "vram_gb": 288, "notes": "8-GPU node, ~$142.42/hr total"},
    "AWS - H100 SXM - p5.4xlarge":          {"provider": "AWS",       "gpu": "H100",  "cost_hr": 6.88,  "vram_gb": 80,  "notes": "1-GPU instance"},
    "AWS - H100 SXM - p5.48xlarge":         {"provider": "AWS",       "gpu": "H100",  "cost_hr": 6.88,  "vram_gb": 80,  "notes": "8-GPU node, ~$55.04/hr total"},
    "AWS - H200 - p5en.48xlarge":           {"provider": "AWS",       "gpu": "H200",  "cost_hr": 7.91,  "vram_gb": 141, "notes": "8-GPU node, ~$63.30/hr total"},
    "AWS - L4 - g6.xlarge":                 {"provider": "AWS",       "gpu": "L4",    "cost_hr": 0.81,  "vram_gb": 24,  "notes": "1-GPU instance"},
    "AWS - L4 - g6.2xlarge":                {"provider": "AWS",       "gpu": "L4",    "cost_hr": 0.98,  "vram_gb": 24,  "notes": "1-GPU instance"},
    "AWS - L4 - g6.4xlarge":                {"provider": "AWS",       "gpu": "L4",    "cost_hr": 1.32,  "vram_gb": 24,  "notes": "1-GPU instance"},
    "AWS - L4 - g6.8xlarge":                {"provider": "AWS",       "gpu": "L4",    "cost_hr": 2.01,  "vram_gb": 24,  "notes": "1-GPU instance"},
    "AWS - L4 - g6.12xlarge":               {"provider": "AWS",       "gpu": "L4",    "cost_hr": 1.15,  "vram_gb": 24,  "notes": "4-GPU node, ~$4.60/hr total"},
    "AWS - L4 - g6.16xlarge":               {"provider": "AWS",       "gpu": "L4",    "cost_hr": 3.40,  "vram_gb": 24,  "notes": "1-GPU instance"},
    "AWS - L4 - g6.24xlarge":               {"provider": "AWS",       "gpu": "L4",    "cost_hr": 1.67,  "vram_gb": 24,  "notes": "4-GPU node, ~$6.68/hr total"},
    "AWS - L4 - g6.48xlarge":               {"provider": "AWS",       "gpu": "L4",    "cost_hr": 1.67,  "vram_gb": 24,  "notes": "8-GPU node, ~$13.35/hr total"},
    "AWS - L4 - gr6.4xlarge":               {"provider": "AWS",       "gpu": "L4",    "cost_hr": 1.54,  "vram_gb": 24,  "notes": "1-GPU instance, RAM-heavy (1:8 vCPU:RAM)"},
    "AWS - L4 - gr6.8xlarge":               {"provider": "AWS",       "gpu": "L4",    "cost_hr": 2.45,  "vram_gb": 24,  "notes": "1-GPU instance, RAM-heavy (1:8 vCPU:RAM)"},
    "AWS - L40S - g6e.xlarge":              {"provider": "AWS",       "gpu": "L40S",  "cost_hr": 1.86,  "vram_gb": 48,  "notes": "1-GPU instance"},
    "AWS - L40S - g6e.2xlarge":             {"provider": "AWS",       "gpu": "L40S",  "cost_hr": 2.24,  "vram_gb": 48,  "notes": "1-GPU instance"},
    "AWS - L40S - g6e.4xlarge":             {"provider": "AWS",       "gpu": "L40S",  "cost_hr": 3.00,  "vram_gb": 48,  "notes": "1-GPU instance"},
    "AWS - L40S - g6e.8xlarge":             {"provider": "AWS",       "gpu": "L40S",  "cost_hr": 4.53,  "vram_gb": 48,  "notes": "1-GPU instance"},
    "AWS - L40S - g6e.12xlarge":            {"provider": "AWS",       "gpu": "L40S",  "cost_hr": 2.62,  "vram_gb": 48,  "notes": "4-GPU node, ~$10.49/hr total"},
    "AWS - L40S - g6e.16xlarge":            {"provider": "AWS",       "gpu": "L40S",  "cost_hr": 7.58,  "vram_gb": 48,  "notes": "1-GPU instance"},
    "AWS - L40S - g6e.24xlarge":            {"provider": "AWS",       "gpu": "L40S",  "cost_hr": 3.77,  "vram_gb": 48,  "notes": "4-GPU node, ~$15.07/hr total"},
    "AWS - L40S - g6e.48xlarge":            {"provider": "AWS",       "gpu": "L40S",  "cost_hr": 3.77,  "vram_gb": 48,  "notes": "8-GPU node, ~$30.13/hr total"},
    "AWS - RTX PRO 4500 - g7.2xlarge":      {"provider": "AWS",       "gpu": "RTX PRO 4500", "cost_hr": 2.52, "vram_gb": 32, "notes": "1-GPU instance"},
    "AWS - RTX PRO 4500 - g7.4xlarge":      {"provider": "AWS",       "gpu": "RTX PRO 4500", "cost_hr": 3.04, "vram_gb": 32, "notes": "1-GPU instance"},
    "AWS - RTX PRO 4500 - g7.8xlarge":      {"provider": "AWS",       "gpu": "RTX PRO 4500", "cost_hr": 4.09, "vram_gb": 32, "notes": "1-GPU instance"},
    "AWS - RTX PRO 4500 - g7.12xlarge":     {"provider": "AWS",       "gpu": "RTX PRO 4500", "cost_hr": 3.56, "vram_gb": 32, "notes": "2-GPU node, ~$7.13/hr total"},
    "AWS - RTX PRO 4500 - g7.24xlarge":     {"provider": "AWS",       "gpu": "RTX PRO 4500", "cost_hr": 3.56, "vram_gb": 32, "notes": "4-GPU node, ~$14.26/hr total"},
    "AWS - RTX PRO 4500 - g7.48xlarge":     {"provider": "AWS",       "gpu": "RTX PRO 4500", "cost_hr": 3.56, "vram_gb": 32, "notes": "8-GPU node, ~$28.51/hr total"},
    "AWS - RTX PRO 6000 - g7e.2xlarge":     {"provider": "AWS",       "gpu": "RTX PRO 6000", "cost_hr": 3.36, "vram_gb": 96, "notes": "1-GPU instance"},
    "AWS - RTX PRO 6000 - g7e.4xlarge":     {"provider": "AWS",       "gpu": "RTX PRO 6000", "cost_hr": 4.00, "vram_gb": 96, "notes": "1-GPU instance"},
    "AWS - RTX PRO 6000 - g7e.8xlarge":     {"provider": "AWS",       "gpu": "RTX PRO 6000", "cost_hr": 5.27, "vram_gb": 96, "notes": "1-GPU instance"},
    "AWS - RTX PRO 6000 - g7e.12xlarge":    {"provider": "AWS",       "gpu": "RTX PRO 6000", "cost_hr": 4.14, "vram_gb": 96, "notes": "2-GPU node, ~$8.29/hr total"},
    "AWS - RTX PRO 6000 - g7e.24xlarge":    {"provider": "AWS",       "gpu": "RTX PRO 6000", "cost_hr": 4.14, "vram_gb": 96, "notes": "4-GPU node, ~$16.57/hr total"},
    "AWS - RTX PRO 6000 - g7e.48xlarge":    {"provider": "AWS",       "gpu": "RTX PRO 6000", "cost_hr": 4.14, "vram_gb": 96, "notes": "8-GPU node, ~$33.14/hr total"},
    # ── Azure ────────────────────────────────────────────────────────────────
    "Azure - A100 40GB - ND96asr v4":       {"provider": "Azure",     "gpu": "A100",  "cost_hr": 3.40,  "vram_gb": 40,  "notes": "8-GPU node, ~$27.20/hr total"},
    "Azure - A100 80GB - NC24ads A100 v4":  {"provider": "Azure",     "gpu": "A100",  "cost_hr": 3.67,  "vram_gb": 80,  "notes": "1-GPU instance"},
    "Azure - A100 80GB - NC48ads A100 v4":  {"provider": "Azure",     "gpu": "A100",  "cost_hr": 3.67,  "vram_gb": 80,  "notes": "2-GPU node, ~$7.35/hr total"},
    "Azure - A100 80GB - NC96ads A100 v4":  {"provider": "Azure",     "gpu": "A100",  "cost_hr": 3.67,  "vram_gb": 80,  "notes": "4-GPU node, ~$14.69/hr total"},
    "Azure - A100 80GB - ND96amsr v4":      {"provider": "Azure",     "gpu": "A100",  "cost_hr": 4.10,  "vram_gb": 80,  "notes": "8-GPU node, ~$32.77/hr total (NDm A100 v4)"},
    "Azure - GB200 - ND GB200 v6":          {"provider": "Azure",     "gpu": "GB200", "cost_hr": 27.04, "vram_gb": 186, "notes": "4-GPU node, ~$108.16/hr total"},
    "Azure - H100 NVL - NC40ads H100 v5":   {"provider": "Azure",     "gpu": "H100",  "cost_hr": 6.98,  "vram_gb": 94,  "notes": "1-GPU instance"},
    "Azure - H100 NVL - NC80adis H100 v5":  {"provider": "Azure",     "gpu": "H100",  "cost_hr": 6.98,  "vram_gb": 94,  "notes": "2-GPU node, ~$13.96/hr total"},
    "Azure - H100 - ND96is H100 v5":        {"provider": "Azure",     "gpu": "H100",  "cost_hr": 11.06, "vram_gb": 80,  "notes": "8-GPU node, ~$88.49/hr total; no-InfiniBand variant (is/is_flex/noIB same price)"},
    "Azure - H100 - ND96isr H100 v5":       {"provider": "Azure",     "gpu": "H100",  "cost_hr": 12.29, "vram_gb": 80,  "notes": "8-GPU node, ~$98.32/hr total"},
    "Azure - H200 - ND H200 v5":            {"provider": "Azure",     "gpu": "H200",  "cost_hr": 10.60, "vram_gb": 141, "notes": "8-GPU node, ~$84.80/hr total (East US 2)"},
    "Azure - MI300X - ND MI300X v5":        {"provider": "Azure",     "gpu": "MI300X", "cost_hr": 6.00, "vram_gb": 192, "notes": "8-GPU node, ~$48.00/hr total (East US 2)"},
    "Azure - RTX PRO 6000 - NC144ds v6":    {"provider": "Azure",     "gpu": "RTX PRO 6000", "cost_hr": 6.38, "vram_gb": 96, "notes": "1-GPU size; NC144lds (local-disk) $5.50"},
    "Azure - RTX PRO 6000 - NC288ds v6":    {"provider": "Azure",     "gpu": "RTX PRO 6000", "cost_hr": 5.50, "vram_gb": 96, "notes": "2-GPU node, ~$11.00/hr total"},
    # ── CoreWeave ────────────────────────────────────────────────────────────
    "CoreWeave - A100 80GB":                {"provider": "CoreWeave", "gpu": "A100",  "cost_hr": 2.70,  "vram_gb": 80,  "notes": "8-GPU node, ~$21.60/hr total"},
    "CoreWeave - B200":                     {"provider": "CoreWeave", "gpu": "B200",  "cost_hr": 8.60,  "vram_gb": 192, "notes": "8-GPU node, ~$68.80/hr total"},
    "CoreWeave - GB200 NVL72":              {"provider": "CoreWeave", "gpu": "GB200", "cost_hr": 10.50, "vram_gb": 186, "notes": "4-GPU node, ~$42.00/hr total"},
    "CoreWeave - GH200":                    {"provider": "CoreWeave", "gpu": "GH200", "cost_hr": 6.50,  "vram_gb": 96,  "notes": "1-GPU instance"},
    "CoreWeave - H100 SXM":                 {"provider": "CoreWeave", "gpu": "H100",  "cost_hr": 6.16,  "vram_gb": 80,  "notes": "8-GPU node, ~$49.24/hr total"},
    "CoreWeave - H200":                     {"provider": "CoreWeave", "gpu": "H200",  "cost_hr": 6.31,  "vram_gb": 141, "notes": "8-GPU node, ~$50.44/hr total"},
    "CoreWeave - L40S":                     {"provider": "CoreWeave", "gpu": "L40S",  "cost_hr": 2.25,  "vram_gb": 48,  "notes": "8-GPU node, ~$18.00/hr total"},
    "CoreWeave - RTX PRO 6000":             {"provider": "CoreWeave", "gpu": "RTX PRO 6000", "cost_hr": 2.50, "vram_gb": 96, "notes": "8-GPU node, ~$20.00/hr total"},
    # ── Crusoe ───────────────────────────────────────────────────────────────
    "Crusoe - A100 SXM 80GB":               {"provider": "Crusoe",    "gpu": "A100",  "cost_hr": 2.30,  "vram_gb": 80,  "notes": "On-demand"},
    "Crusoe - A100 PCIe 80GB":              {"provider": "Crusoe",    "gpu": "A100",  "cost_hr": 2.00,  "vram_gb": 80,  "notes": "On-demand"},
    "Crusoe - H100 HGX":                    {"provider": "Crusoe",    "gpu": "H100",  "cost_hr": 3.90,  "vram_gb": 80,  "notes": "On-demand"},
    "Crusoe - H200 HGX":                    {"provider": "Crusoe",    "gpu": "H200",  "cost_hr": 4.29,  "vram_gb": 141, "notes": "On-demand"},
    "Crusoe - L40S":                        {"provider": "Crusoe",    "gpu": "L40S",  "cost_hr": 1.50,  "vram_gb": 48,  "notes": "On-demand"},
    "Crusoe - MI300X":                      {"provider": "Crusoe",    "gpu": "MI300X", "cost_hr": 3.45, "vram_gb": 192, "notes": "On-demand"},
    # ── GCP ──────────────────────────────────────────────────────────────────
    "GCP - A100 40GB - a2-highgpu-1g":      {"provider": "GCP",       "gpu": "A100",  "cost_hr": 3.67,  "vram_gb": 40,  "notes": "1-GPU instance"},
    "GCP - A100 40GB - a2-highgpu-2g":      {"provider": "GCP",       "gpu": "A100",  "cost_hr": 3.67,  "vram_gb": 40,  "notes": "2-GPU node, ~$7.35/hr total"},
    "GCP - A100 40GB - a2-highgpu-4g":      {"provider": "GCP",       "gpu": "A100",  "cost_hr": 3.67,  "vram_gb": 40,  "notes": "4-GPU node, ~$14.69/hr total"},
    "GCP - A100 40GB - a2-highgpu-8g":      {"provider": "GCP",       "gpu": "A100",  "cost_hr": 3.67,  "vram_gb": 40,  "notes": "8-GPU node, ~$29.39/hr total"},
    "GCP - A100 40GB - a2-megagpu-16g":     {"provider": "GCP",       "gpu": "A100",  "cost_hr": 3.48,  "vram_gb": 40,  "notes": "16-GPU node, ~$55.74/hr total"},
    "GCP - A100 80GB - a2-ultragpu-1g":     {"provider": "GCP",       "gpu": "A100",  "cost_hr": 5.07,  "vram_gb": 80,  "notes": "1-GPU instance"},
    "GCP - A100 80GB - a2-ultragpu-2g":     {"provider": "GCP",       "gpu": "A100",  "cost_hr": 5.07,  "vram_gb": 80,  "notes": "2-GPU node, ~$10.14/hr total"},
    "GCP - A100 80GB - a2-ultragpu-4g":     {"provider": "GCP",       "gpu": "A100",  "cost_hr": 5.07,  "vram_gb": 80,  "notes": "4-GPU node, ~$20.28/hr total"},
    "GCP - A100 80GB - a2-ultragpu-8g":     {"provider": "GCP",       "gpu": "A100",  "cost_hr": 5.07,  "vram_gb": 80,  "notes": "8-GPU node, ~$40.55/hr total"},
    "GCP - H100 SXM - a3-highgpu-8g":       {"provider": "GCP",       "gpu": "H100",  "cost_hr": 11.06, "vram_gb": 80,  "notes": "8-GPU node, ~$88.49/hr total"},
    "GCP - H100 SXM - a3-megagpu-8g":       {"provider": "GCP",       "gpu": "H100",  "cost_hr": 11.68, "vram_gb": 80,  "notes": "8-GPU node, ~$93.40/hr total (Mega, GPUDirect-TCPXO)"},
    "GCP - H200 - a3-ultragpu-8g":          {"provider": "GCP",       "gpu": "H200",  "cost_hr": 10.60, "vram_gb": 141, "notes": "8-GPU node, ~$84.81/hr total"},
    "GCP - L4 - g2-standard-4":             {"provider": "GCP",       "gpu": "L4",    "cost_hr": 0.71,  "vram_gb": 24,  "notes": "1-GPU instance"},
    "GCP - L4 - g2-standard-8":             {"provider": "GCP",       "gpu": "L4",    "cost_hr": 0.85,  "vram_gb": 24,  "notes": "1-GPU instance"},
    "GCP - L4 - g2-standard-12":            {"provider": "GCP",       "gpu": "L4",    "cost_hr": 1.00,  "vram_gb": 24,  "notes": "1-GPU instance"},
    "GCP - L4 - g2-standard-16":            {"provider": "GCP",       "gpu": "L4",    "cost_hr": 1.15,  "vram_gb": 24,  "notes": "1-GPU instance"},
    "GCP - L4 - g2-standard-24":            {"provider": "GCP",       "gpu": "L4",    "cost_hr": 1.00,  "vram_gb": 24,  "notes": "2-GPU node, ~$2.00/hr total"},
    "GCP - L4 - g2-standard-32":            {"provider": "GCP",       "gpu": "L4",    "cost_hr": 1.73,  "vram_gb": 24,  "notes": "1-GPU instance"},
    "GCP - L4 - g2-standard-48":            {"provider": "GCP",       "gpu": "L4",    "cost_hr": 1.00,  "vram_gb": 24,  "notes": "4-GPU node, ~$4.00/hr total"},
    "GCP - L4 - g2-standard-96":            {"provider": "GCP",       "gpu": "L4",    "cost_hr": 1.00,  "vram_gb": 24,  "notes": "8-GPU node, ~$8.00/hr total"},
    "GCP - RTX PRO 6000 - g4-standard-48":  {"provider": "GCP",       "gpu": "RTX PRO 6000", "cost_hr": 4.50, "vram_gb": 96, "notes": "1-GPU instance"},
    "GCP - RTX PRO 6000 - g4-standard-96":  {"provider": "GCP",       "gpu": "RTX PRO 6000", "cost_hr": 4.50, "vram_gb": 96, "notes": "2-GPU node, ~$9.00/hr total"},
    "GCP - RTX PRO 6000 - g4-standard-192": {"provider": "GCP",       "gpu": "RTX PRO 6000", "cost_hr": 4.50, "vram_gb": 96, "notes": "4-GPU node, ~$18.00/hr total"},
    "GCP - RTX PRO 6000 - g4-standard-384": {"provider": "GCP",       "gpu": "RTX PRO 6000", "cost_hr": 4.50, "vram_gb": 96, "notes": "8-GPU node, ~$36.00/hr total"},
    # ── Lambda ───────────────────────────────────────────────────────────────
    "Lambda - A100 SXM 40GB":               {"provider": "Lambda",    "gpu": "A100",  "cost_hr": 1.99,  "vram_gb": 40,  "notes": "1-GPU instance"},
    "Lambda - A100 SXM 80GB":               {"provider": "Lambda",    "gpu": "A100",  "cost_hr": 2.79,  "vram_gb": 80,  "notes": "8-GPU node pricing"},
    "Lambda - B200 SXM":                    {"provider": "Lambda",    "gpu": "B200",  "cost_hr": 6.69,  "vram_gb": 192, "notes": "8-GPU node pricing"},
    "Lambda - GH200":                       {"provider": "Lambda",    "gpu": "GH200", "cost_hr": 2.29,  "vram_gb": 96,  "notes": "1-GPU instance"},
    "Lambda - H100 PCIe":                   {"provider": "Lambda",    "gpu": "H100",  "cost_hr": 3.29,  "vram_gb": 80,  "notes": "1-GPU instance"},
    "Lambda - H100 SXM":                    {"provider": "Lambda",    "gpu": "H100",  "cost_hr": 3.99,  "vram_gb": 80,  "notes": "8-GPU node pricing"},
    # ── RunPod ───────────────────────────────────────────────────────────────
    "RunPod - A100 PCIe 80GB":              {"provider": "RunPod",    "gpu": "A100",  "cost_hr": 1.39,  "vram_gb": 80,  "notes": "Secure Cloud on-demand"},
    "RunPod - A100 SXM 80GB":               {"provider": "RunPod",    "gpu": "A100",  "cost_hr": 1.59,  "vram_gb": 80,  "notes": "Secure Cloud on-demand"},
    "RunPod - B200":                        {"provider": "RunPod",    "gpu": "B200",  "cost_hr": 6.79,  "vram_gb": 192, "notes": "Secure Cloud on-demand"},
    "RunPod - B300":                        {"provider": "RunPod",    "gpu": "B300",  "cost_hr": 7.89,  "vram_gb": 288, "notes": "Secure Cloud on-demand"},
    "RunPod - H100 NVL":                    {"provider": "RunPod",    "gpu": "H100",  "cost_hr": 3.19,  "vram_gb": 94,  "notes": "Secure Cloud on-demand"},
    "RunPod - H100 PCIe":                   {"provider": "RunPod",    "gpu": "H100",  "cost_hr": 2.89,  "vram_gb": 80,  "notes": "Secure Cloud on-demand"},
    "RunPod - H100 SXM":                    {"provider": "RunPod",    "gpu": "H100",  "cost_hr": 3.29,  "vram_gb": 80,  "notes": "Secure Cloud on-demand"},
    "RunPod - H200 SXM":                    {"provider": "RunPod",    "gpu": "H200",  "cost_hr": 4.59,  "vram_gb": 141, "notes": "Secure Cloud on-demand"},
    "RunPod - L4":                          {"provider": "RunPod",    "gpu": "L4",    "cost_hr": 0.49,  "vram_gb": 24,  "notes": "Secure Cloud on-demand"},
    "RunPod - L40S":                        {"provider": "RunPod",    "gpu": "L40S",  "cost_hr": 0.99,  "vram_gb": 48,  "notes": "Secure Cloud on-demand"},
    "RunPod - RTX PRO 6000":                {"provider": "RunPod",    "gpu": "RTX PRO 6000", "cost_hr": 2.09, "vram_gb": 96, "notes": "Secure Cloud on-demand"},
    # ── Together AI ──────────────────────────────────────────────────────────
    "Together - B200":                      {"provider": "Together",  "gpu": "B200",  "cost_hr": 8.19,  "vram_gb": 192, "notes": "GPU cluster on-demand"},
    "Together - H100":                      {"provider": "Together",  "gpu": "H100",  "cost_hr": 3.99,  "vram_gb": 80,  "notes": "GPU cluster on-demand"},
    "Together - H200":                      {"provider": "Together",  "gpu": "H200",  "cost_hr": 5.99,  "vram_gb": 141, "notes": "GPU cluster on-demand"},
    # ── Vast.ai ──────────────────────────────────────────────────────────────
    "Vast.ai - A100 SXM 80GB":              {"provider": "Vast.ai",   "gpu": "A100",  "cost_hr": 1.16,  "vram_gb": 80,  "notes": "Marketplace median, verified hosts, 80GB only (n=10, 3 of 4 samples)"},
    "Vast.ai - B200":                       {"provider": "Vast.ai",   "gpu": "B200",  "cost_hr": 7.75,  "vram_gb": 192, "notes": "Marketplace median, verified hosts (n=19, stable)"},
    "Vast.ai - H100 SXM":                   {"provider": "Vast.ai",   "gpu": "H100",  "cost_hr": 3.07,  "vram_gb": 80,  "notes": "Marketplace median, verified hosts (n=17, stable); US-only subset is ~4.77"},
    "Vast.ai - H200":                       {"provider": "Vast.ai",   "gpu": "H200",  "cost_hr": 4.08,  "vram_gb": 141, "notes": "Marketplace median, verified hosts (n=13, stable)"},
    "Vast.ai - L4":                         {"provider": "Vast.ai",   "gpu": "L4",    "cost_hr": 0.33,  "vram_gb": 24,  "notes": "Marketplace median, verified hosts (n=6); sits on the 0.335 rounding boundary"},
    "Vast.ai - L40S":                       {"provider": "Vast.ai",   "gpu": "L40S",  "cost_hr": 0.80,  "vram_gb": 48,  "notes": "Marketplace median, verified hosts (n=6)"},
    "Vast.ai - RTX PRO 6000":               {"provider": "Vast.ai",   "gpu": "RTX PRO 6000", "cost_hr": 1.52, "vram_gb": 96, "notes": "Marketplace median, Server Edition (n=20, stable across 5 samples)"},
}

GPU_PROVIDERS = sorted(set(v["provider"] for v in GPU_LIBRARY.values()))
