"""
API Model Library — per-token inference pricing
Pricing as of July 9, 2026

Sources: developers.openai.com/api/docs/pricing, platform.claude.com/docs,
         ai.google.dev/gemini-api/docs/pricing, docs.x.ai/docs/models,
         api-docs.deepseek.com, openrouter.ai
"""

# Prices are in $ per 1M tokens
MODEL_LIBRARY = {
    "GPT-5.5 Pro":           {"provider": "OpenAI",    "input": 30,    "output": 180,   "notes": "Top-tier reasoning model, Jun 2026"},
    "GPT-5.5":               {"provider": "OpenAI",    "input": 5,     "output": 30,    "notes": "Flagship, Jun 2026"},
    "GPT-5.4 Pro":           {"provider": "OpenAI",    "input": 30,    "output": 180,   "notes": "Reasoning model, Mar 2026"},
    "GPT-5.4":               {"provider": "OpenAI",    "input": 2.5,   "output": 15,    "notes": "Previous flagship, Feb 2026"},
    "GPT-5.4 Mini":          {"provider": "OpenAI",    "input": 0.75,  "output": 4.5,   "notes": "Mid-tier 5.4 variant, Mar 2026"},
    "GPT-5.4 Nano":          {"provider": "OpenAI",    "input": 0.20,  "output": 1.25,  "notes": "Efficient 5.4 variant, Mar 2026"},
    "GPT-5.3":               {"provider": "OpenAI",    "input": 1.75,  "output": 14,    "notes": "Chat-optimized, now gpt-5.3-codex/-chat"},
    "GPT-5.2 Pro":           {"provider": "OpenAI",    "input": 21,    "output": 168,   "notes": "Reasoning variant, 400K context (Mar 2026 halving reverted)"},
    "GPT-5.2":               {"provider": "OpenAI",    "input": 1.75,  "output": 14,    "notes": "Dec 2025 flagship (Mar 2026 halving reverted)"},
    "GPT-5.1":               {"provider": "OpenAI",    "input": 1.25,  "output": 10,    "notes": "Coding-optimized (Mar 2026 halving reverted)"},
    "GPT-5":                 {"provider": "OpenAI",    "input": 1.25,  "output": 10,    "notes": "Aug 2025 flagship, 400K context"},
    "GPT-5 Mini":            {"provider": "OpenAI",    "input": 0.25,  "output": 2,     "notes": "Efficient mid-tier, great value"},
    "GPT-5 Nano":            {"provider": "OpenAI",    "input": 0.05,  "output": 0.4,   "notes": "Cheapest OpenAI option"},
    "GPT-4.1":               {"provider": "OpenAI",    "input": 2,     "output": 8,     "notes": "Strong all-rounder, 1M context"},
    "GPT-4.1 Mini":          {"provider": "OpenAI",    "input": 0.4,   "output": 1.6,   "notes": "Efficient mid-tier, 1M context"},
    "GPT-4.1 Nano":          {"provider": "OpenAI",    "input": 0.1,   "output": 0.4,   "notes": "Fastest & cheapest GPT-4.1"},
    "o3":                    {"provider": "OpenAI",    "input": 2,     "output": 8,     "notes": "Reasoning model, price dropped Mar 2026"},
    "o3-mini":               {"provider": "OpenAI",    "input": 1.1,   "output": 4.4,   "notes": "Affordable reasoning model"},
    "o4-mini":               {"provider": "OpenAI",    "input": 1.1,   "output": 4.4,   "notes": "Affordable reasoning model"},
    "o1":                    {"provider": "OpenAI",    "input": 15,    "output": 60,    "notes": "Legacy reasoning, high-cost"},
    "Claude Fable 5":        {"provider": "Anthropic", "input": 10,    "output": 50,    "notes": "Most capable GA Anthropic model, 1M context, Jun 2026"},
    "Claude Opus 4.8":       {"provider": "Anthropic", "input": 5,     "output": 25,    "notes": "Agentic coding flagship, 1M context, Jun 2026"},
    "Claude Sonnet 5":       {"provider": "Anthropic", "input": 3,     "output": 15,    "notes": "Intro pricing $2/$10 through Aug 2026"},
    "Claude Haiku 4.5":      {"provider": "Anthropic", "input": 1,     "output": 5,     "notes": "Fast & efficient, great for routing"},
    "Claude Opus 4.7":       {"provider": "Anthropic", "input": 5,     "output": 25,    "notes": "1M context; new tokenizer (~30% more tokens)"},
    "Claude Opus 4.6":       {"provider": "Anthropic", "input": 5,     "output": 25,    "notes": "Previous Opus generation, 1M context"},
    "Claude Sonnet 4.6":     {"provider": "Anthropic", "input": 3,     "output": 15,    "notes": "Previous Sonnet, 1M context"},
    "Claude Opus 4.5":       {"provider": "Anthropic", "input": 5,     "output": 25,    "notes": "Legacy Opus"},
    "Claude Sonnet 4.5":     {"provider": "Anthropic", "input": 3,     "output": 15,    "notes": "Legacy Sonnet"},
    "Gemini 3.5 Flash":      {"provider": "Google",    "input": 1.5,   "output": 9,     "notes": "Latest Google flagship, Jun 2026"},
    "Gemini 3.1 Pro":        {"provider": "Google",    "input": 2,     "output": 12,    "notes": "Preview; ≤200K-token prompt pricing"},
    "Gemini 3 Flash":        {"provider": "Google",    "input": 0.5,   "output": 3,     "notes": "Preview; Pro-grade reasoning at Flash speed"},
    "Gemini 3.1 Flash Lite": {"provider": "Google",    "input": 0.25,  "output": 1.5,   "notes": "Cost-efficient 3.1 variant, Mar 2026"},
    "Gemini 2.5 Pro":        {"provider": "Google",    "input": 1.25,  "output": 10,    "notes": "Production-ready, 1M context"},
    "Gemini 2.5 Flash":      {"provider": "Google",    "input": 0.3,   "output": 2.5,   "notes": "Capable budget option"},
    "Gemini 2.5 Flash-Lite": {"provider": "Google",    "input": 0.1,   "output": 0.4,   "notes": "Cheapest Google model"},
    "Grok 4.5":              {"provider": "xAI",       "input": 2,     "output": 6,     "notes": "New flagship, Jun 2026"},
    "Grok 4.3":              {"provider": "xAI",       "input": 1.25,  "output": 2.5,   "notes": "Mid-tier Grok"},
    "Grok 4.20":             {"provider": "xAI",       "input": 1.25,  "output": 2.5,   "notes": "2M context (price cut from $2/$6)"},
    "Mistral Large 3":       {"provider": "Mistral",   "input": 0.5,   "output": 1.5,   "notes": "675B params, via Mistral API"},
    "Mistral Medium 3.5":    {"provider": "Mistral",   "input": 1.5,   "output": 7.5,   "notes": "New mid-tier, Jun 2026. Via OpenRouter."},
    "Mistral Medium 3":      {"provider": "Mistral",   "input": 0.4,   "output": 2,     "notes": "Enterprise-grade, 131K context. Via OpenRouter."},
    "Mistral Small 4":       {"provider": "Mistral",   "input": 0.15,  "output": 0.6,   "notes": "Hybrid reasoning, multimodal, 262K context. Via OpenRouter."},
    "DeepSeek V4 Pro":       {"provider": "DeepSeek",  "input": 0.435, "output": 0.87,  "notes": "DeepSeek top model, Jun 2026"},
    "DeepSeek V4 Flash":     {"provider": "DeepSeek",  "input": 0.14,  "output": 0.28,  "notes": "Replaces V3.2 chat/reasoner endpoints"},
    "Qwen3.7 Max":           {"provider": "Alibaba",   "input": 1.25,  "output": 3.75,  "notes": "Qwen flagship, Jun 2026. Via OpenRouter."},
    "Qwen3.7 Plus":          {"provider": "Alibaba",   "input": 0.32,  "output": 1.28,  "notes": "Qwen mid-tier, Jun 2026. Via OpenRouter."},
    "Qwen3 Max":             {"provider": "Alibaba",   "input": 0.78,  "output": 3.9,   "notes": "Previous Qwen flagship, 262K context. Via OpenRouter."},
    "Qwen3.5 Plus":          {"provider": "Alibaba",   "input": 0.26,  "output": 1.56,  "notes": "Feb 2026 snapshot. Via OpenRouter."},
    "Qwen3.5 397B A17B":     {"provider": "Alibaba",   "input": 0.385, "output": 2.45,  "notes": "Open-weights 397B MoE (17B active), vision-language. Via OpenRouter."},
    "Qwen3 235B A22B":       {"provider": "Alibaba",   "input": 0.455, "output": 1.82,  "notes": "Open-weights 235B MoE (22B active), Instruct. Via OpenRouter."},
    "Kimi K2.6":             {"provider": "Moonshot",   "input": 0.65,  "output": 3.41,  "notes": "Current kimi-latest. Via OpenRouter."},
    "Kimi K2.5":             {"provider": "Moonshot",   "input": 0.375, "output": 2.025, "notes": "Strong coding & math, 262K context. Via OpenRouter."},
    "MiniMax M3":            {"provider": "MiniMax",    "input": 0.3,   "output": 1.2,   "notes": "Latest MiniMax flagship, Jun 2026. Via OpenRouter."},
    "MiniMax M2.7":          {"provider": "MiniMax",    "input": 0.18,  "output": 0.72,  "notes": "Previous flagship (price cut Jul 2026). Via OpenRouter."},
    "MiniMax M2.5":          {"provider": "MiniMax",    "input": 0.12,  "output": 0.48,  "notes": "Older flagship (price cut Jul 2026). Via OpenRouter."},
    "MiniMax M2-Her":        {"provider": "MiniMax",    "input": 0.3,   "output": 1.2,   "notes": "65K context. Via OpenRouter."},
    "Llama 4 Maverick":      {"provider": "Meta",       "input": 0.15,  "output": 0.6,   "notes": "Open-weights 400B MoE (17B active). Via OpenRouter."},
    "Llama 4 Scout":         {"provider": "Meta",       "input": 0.10,  "output": 0.3,   "notes": "Open-weights, efficient Llama 4 variant. Via OpenRouter."},
    "Arcee Trinity Nano":    {"provider": "Arcee AI",   "input": None,  "output": None,  "notes": "Open-weights 6B MoE (1B active), 128K context. Self-hosted only."},
}

API_MODELS = [name for name, m in MODEL_LIBRARY.items() if m["input"] is not None]
